### PR TITLE
mark repository as abandoned

### PR DESCRIPTION
**Pull request by aschleifer**

### CODE REVIEW

**Comment by Arutha2580** [comment]
Maybe also flag it abandoned in the composer.json file? https://getcomposer.org/doc/04-schema.md#abandoned

**Comment by T4cC0re** [comment]
And don't forget to archive the repo in project settings afterwards 😄

**Comment by aschleifer** [comment]
> Maybe also flag it abandoned in the composer.json file? https://getcomposer.org/doc/04-schema.md#abandoned

done

**Comment by Arutha2580** [comment]
I do not have an approve button :) but it looks fine for me now

**Pull request merged**
